server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/beebook
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
            format_sql: true
            show_sql: true
    servlet:
        multipart:
            maxFileSize: -1

mailServer:
    host: smtp.gmail.com
    port: 587
    email: hadzvodich@gmail.com
    password: zbnzwdnarohkhoyf
    protocol: smtp
    isSSL: false

